export const colorIndex: Record<string, string> = {
    // "#fff": "var(--gm3-sys-color-background)",
    "#b3261e": "var(--gm3-sys-color-error)",
    "#f9dedc": "var(--gm3-sys-color-error-container)",
    "#f2f2f2": "var(--gm3-sys-color-inverse-on-surface)",
    "#a8c7fa": "var(--gm3-sys-color-inverse-primary)",
    "#303030": "var(--gm3-sys-color-inverse-surface)",
    // "#1f1f1f": "var(--gm3-sys-color-on-background)",
    // "#fff": "var(--gm3-sys-color-on-error)",
    "#410e0b": "var(--gm3-sys-color-on-error-container)",
    // "#fff": "var(--gm3-sys-color-on-primary)",
    "#041e49": "var(--gm3-sys-color-on-primary-container)",
    // "#041e49": "var(--gm3-sys-color-on-primary-fixed)",
    "#0842a0": "var(--gm3-sys-color-on-primary-fixed-variant)",
    // "#fff": "var(--gm3-sys-color-on-secondary)",
    "#001d35": "var(--gm3-sys-color-on-secondary-container)",
    // "#001d35": "var(--gm3-sys-color-on-secondary-fixed)",
    "#004a77": "var(--gm3-sys-color-on-secondary-fixed-variant)",
    "#1f1f1f": "var(--gm3-sys-color-on-surface)",
    "#444746": "var(--gm3-sys-color-on-surface-variant)",
    // "#fff": "var(--gm3-sys-color-on-tertiary)",
    "#072711": "var(--gm3-sys-color-on-tertiary-container)",
    // "#072711": "var(--gm3-sys-color-on-tertiary-fixed)",
    "#0f5223": "var(--gm3-sys-color-on-tertiary-fixed-variant)",
    "#747775": "var(--gm3-sys-color-outline)",
    "#c4c7c5": "var(--gm3-sys-color-outline-variant)",
    "#0b57d0": "var(--gm3-sys-color-primary)",
    "#d3e3fd": "var(--gm3-sys-color-primary-container)",
    // "#d3e3fd": "var(--gm3-sys-color-primary-fixed)",
    // "#a8c7fa": "var(--gm3-sys-color-primary-fixed-dim)",
    // "#000": "var(--gm3-sys-color-scrim)",
    "#00639b": "var(--gm3-sys-color-secondary)",
    "#c2e7ff": "var(--gm3-sys-color-secondary-container)",
    // "#c2e7ff": "var(--gm3-sys-color-secondary-fixed)",
    "#7fcfff": "var(--gm3-sys-color-secondary-fixed-dim)",
    "#000": "var(--gm3-sys-color-shadow)",
    "#fff": "var(--gm3-sys-color-surface-container-lowest)",
    // "#fff": "var(--gm3-sys-color-surface)",
    "#d3dbe5": "var(--gm3-sys-color-surface-dim)",
    "#f8fafd": "var(--gm3-sys-color-surface-container-low)",
    "#f0f4f9": "var(--gm3-sys-color-surface-container)",
    "#e9eef6": "var(--gm3-sys-color-surface-container-high)",
    "#dde3ea": "var(--gm3-sys-color-surface-container-highest)",
    // "#fff": "var(--gm3-sys-color-surface-bright)",
    "#e1e3e1": "var(--gm3-sys-color-surface-variant)",
    "#6991d6": "var(--gm3-sys-color-surface-tint)",
    "#146c2e": "var(--gm3-sys-color-tertiary)",
    "#c4eed0": "var(--gm3-sys-color-tertiary-container)",
    // "#c4eed0": "var(--gm3-sys-color-tertiary-fixed)",
    "#6dd58c": "var(--gm3-sys-color-tertiary-fixed-dim)",

    // Docs
    "#185abc": "var(--gm3-sys-color-primary)",
    "#1a73e8": "var(--gm3-sys-color-primary)",
    "#1e64d4": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 8%)",
    "#296bd6": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 12%)",
    "#4285f4": "var(--gm3-sys-color-primary)",
    "#4d90fe": "var(--gm3-sys-color-primary)",
    "rgba(11,87,208,.08)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 8%)",
    "rgba(11,87,208,.12)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 12%)",
    "rgba(66,133,244,.12)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 12%)",
    "rgba(66,133,244,.32)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 32%)",

    // Slides
    "hsla(0,0%,100%,.95)": "var(--gm3-sys-color-surface-container)",

    "#fffdf6": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#fff7e1": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#fff5d7": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 18%)",
    "#fee8ac": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 30%)",
    "#feefc3": "var(--gm3-sys-color-primary-container)",

    "#f8f9fa": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",

    "#fbbc04": "var(--gm3-sys-color-primary)",
    "#fbc117": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 8%)",
    "#fdc154": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 12%)",

    // Sheets
    
    "#b31412": "var(--gm3-sys-color-error)",
    "#d93025": "var(--gm3-sys-color-error)",

    "#bbe2c6": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 50%)",
    "#c8e7d1": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 30%)",
    "rgba(24,128,56,.04)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 8%)",
    "rgba(24,128,56,.1)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 12%)",
    "rgba(24,128,56,.12)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 16%)",
    "#ceead6": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#f8fcf9": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#e7f5eb": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#dff2e4": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 18%)",
    "#e6f4ea": "var(--gm3-sys-color-primary-container)",

    "#137333": "var(--gm3-sys-color-primary)",
    "#188038": "var(--gm3-sys-color-primary)",
    "#2a8947": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 8%)",
    "#34a853": "var(--gm3-sys-color-primary)",
    "#4f9e67": "color-mix(in oklab, var(--gm3-sys-color-primary), var(--gm3-sys-color-on-primary) 12%)",

    // Gmail
    "#0000CC": "var(--gm3-sys-color-primary)",
    "#15c": "var(--gm3-sys-color-primary)",
    "rgb(23,78,166)": "var(--gm3-sys-color-primary)",
    "rgba(26,115,232,.8)": "color-mix(in oklab, var(--gm3-sys-color-primary), transparent 8%)",
    "rgba(26,115,232,.12)": "color-mix(in oklab, var(--gm3-sys-color-primary), transparent 12%)",
    "rgba(26,115,232,.16)": "color-mix(in oklab, var(--gm3-sys-color-primary), transparent 16%)",
    "rgb(26,115,232)": "var(--gm3-sys-color-primary)",
    "rgb(25,103,210)": "var(--gm3-sys-color-primary)",
    "rgb(138,180,248)": "var(--gm3-sys-color-inverse-primary)",
    "rgb(218,220,224)": "var(--gm3-sys-color-outline)",

    "#f2f6fc": "var(--gm3-sys-color-surface)",

    "#c2dbff": "var(--gm3-sys-color-primary-container)",
    "#c3d9ff": "var(--gm3-sys-color-primary-container)",

    "rgb(210,227,252)": "var(--gm3-sys-color-primary-container)",
    "rgba(255,255,255,0.95)": "var(--gm3-sys-color-surface)",
    "rgba(255,255,255,1)": "var(--gm3-sys-color-surface)",
    "rgba(241,243,244,0.87)": "var(--gm3-sys-color-surface-container-low)",

    "rgba(100,121,143,0.12)": "var(--gm3-sys-color-outline-variant)",
    "hsl(0,0%,49%)": "var(--gm3-sys-color-on-surface-variant)",

    "#dd4b39": "var(--gm3-sys-color-error)",
    "rgb(197,34,31)": "var(--gm3-sys-color-error)",
    // PLACEHOLDER
    "#f0c36d": "var(--gm3-sys-color-primary)",
    "#f9edbe": "var(--gm3-sys-color-primary-container)",
    "#fff1a8": "var(--gm3-sys-color-primary-container)",

    // Google Classroom
    "rgb(241,243,244)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "rgb(248,249,250)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "rgb(232,234,237)": "var(--gm3-sys-color-inverse-on-surface)",
    "rgba(0,0,0,.549)": "var(--gm3-sys-color-outline)",

    // \/ HACK: Adjust replace-colors to have 0. prefix for matching.
    // In addition, three digit hex codes should also match six digit hex codes
    "rgba(0,0,0,0.87)":  "var(--gm3-sys-color-on-surface)",
    "#ffffff":  "var(--gm3-sys-color-surface)",
    "rgba(66,133,244,.1)": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 16%)",
    "rgb(232,240,254)": "var(--gm3-sys-color-primary-container)",

    // Main

    "rgba(0,0,0,.04)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 4%)",
    'rgba(0,0,0,.12)': "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 12%)",
    "rgba(0,0,0,.54)": "var(--gm3-sys-color-on-surface)",
    "rgba(0,0,0,.6)": "var(--gm3-sys-color-on-surface)",
    "rgba(0,0,0,.7)": "var(--gm3-sys-color-on-surface)",
    "rgba(0,0,0,.87)":  "var(--gm3-sys-color-on-surface)",
    "rgb(32,33,36)":  "var(--gm3-sys-color-on-surface)",
    "rgb(60,64,67)": "var(--gm3-sys-color-inverse-surface)",
    "rgba(60,64,67,0.1)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 10%)",
    "rgba(60,64,67,.9)": "var(--gm3-sys-color-inverse-surface)",
    "rgba(60,64,67,.15)": "color-mix(in oklab, transparent, var(--gm3-sys-color-shadow) 15%)",
    "rgba(60,64,67,.38)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 38%)",
    "rgba(68,71,70,.08)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "rgba(68,71,70,.12)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 12%)",
    "rgb(95,99,104)": "var(--gm3-sys-color-on-surface)",
    "#202124": "var(--gm3-sys-color-on-surface)",
    "#222": "var(--gm3-sys-color-on-surface)",
    "#333": "var(--gm3-sys-color-on-surface)",
    "#444": "var(--gm3-sys-color-on-surface)",
    "#3c4043": "var(--gm3-sys-color-on-surface)",
    "#5e5e5e": "var(--gm3-sys-color-on-surface-variant)",
    "#5f6368": "var(--gm3-sys-color-on-surface-variant)",
    "#616161": "var(--gm3-sys-color-on-surface-variant)",
    "#646464": "var(--gm3-sys-color-on-surface-variant)",
    "#666": "var(--gm3-sys-color-on-surface-variant)",
    "#676767": "var(--gm3-sys-color-on-surface-variant)",
    "#70757a": "var(--gm3-sys-color-on-surface-variant)",
    "#777": "var(--gm3-sys-color-outline)",
    "#80868b": "var(--gm3-sys-color-outline)",
    "#9aa0a6": "var(--gm3-sys-color-outline)",
    "#abcfe7": "color-mix(in oklab, var(--gm3-sys-color-secondary-container), var(--gm3-sys-color-on-secondary-container) 16%)",
    "#b2d7ef": "color-mix(in oklab, var(--gm3-sys-color-secondary-container), var(--gm3-sys-color-on-secondary-container) 8%)",
    "#b9cbe7": "color-mix(in oklab, var(--gm3-sys-color-primary-container), var(--gm3-sys-color-on-primary-container) 16%)",
    "#bbd4fb": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 30%)",
    "#c1d8fb": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 50%)",
    "#c7c7c7": "var(--gm3-sys-color-outline-variant)",
    "#cbdbf6": "color-mix(in oklab, var(--gm3-sys-color-primary-container), var(--gm3-sys-color-on-primary-container) 8%)",
    "#ccc": "var(--gm3-sys-color-outline-variant)",
    "#cce0fc": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary-fixed-dim) 50%)",
    "#dadce0": "var(--gm3-sys-color-outline-variant)",
    "gray": "var(--gm3-sys-color-outline-variant)",
    "#d5dae1": "color-mix(in oklab, var(--gm3-sys-color-surface-container-high), var(--gm3-sys-color-on-surface) 12%)",
    "#dae3f2": "color-mix(in oklab, var(--gm3-sys-color-surface-container-high), var(--gm3-sys-color-on-surface) 16%)",
    "#dce1e8": "color-mix(in oklab, var(--gm3-sys-color-surface-container-high), var(--gm3-sys-color-on-surface) 8%)",
    "#dfe7f3": "color-mix(in oklab, var(--gm3-sys-color-surface-container-high), var(--gm3-sys-color-on-surface) 8%)",
    "#d4dce8": "color-mix(in oklab, var(--gm3-sys-color-surface-container-highest), var(--gm3-sys-color-on-surface) 8%)",
    // Disabled BG
    "rgba(31,31,31,.12)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 12%)",
    "rgba(31,31,31,.38)": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 38%)",
    "#e0e0e0": "var(--gm3-sys-color-outline)",
    "#e1e9f7": "color-mix(in oklab, transparent, var(--gm3-sys-color-primary) 16%)",
    "#d8e5f8": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 18%)",
    "#cfdff6": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 20%)",
    "#e1ecfe": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 18%)",
    "#e4e4e4": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#e5e5e5": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#e8f0fe": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#e9f1fe": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#ebebeb": "var(--gm3-sys-color-outline-variant)",
    "#eee": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#eeeeee": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#edf2fa": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#e7edf8": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#f1f1f1": "var(--gm3-sys-color-surface-container)",
    "#f3f6fc": "var(--gm3-sys-color-surface-container)",
    "#f4f4f4": "var(--gm3-sys-color-surface-container)",
    "#f5f5f5": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",
    "#f8f8f8": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#f9fbfd": "var(--gm3-sys-color-surface-container-lowest)",
    
    "#e8ebee": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#e1e3e6": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 12%)",
    "#e8eaed": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 12%)",
    "#d2e3fc": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 16%)",

    // Menu item highlight
    "#f1f3f4": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",
    "#f8fbff": "color-mix(in oklab, transparent, var(--gm3-sys-color-on-surface) 8%)",

    "white": "var(--gm3-sys-color-surface-container-lowest)",
    "transparent": "var(--transparent, transparent)"
};
